import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";

import Navbar from "./components/Navbar";

const firaCode = Fira_Code({ weight: ["300", "500", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jonah's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${firaCode.className} font-light`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
